version: '3.8'

services:
  automation-tests:
    build: .
    container_name: enocta-tests
    environment:
      - BROWSER=${BROWSER:-chrome}
      - TAGS=${TAGS:-}
      - CI=true
    volumes:
      - ./target:/app/target
